#! /bin/sh
# /etc/init.d/noip 

### BEGIN INIT INFO
# Provides:          camera 
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start camera at boot. 
# Description:       Start camera at boot.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting camera"
    su pi -c 'cd /home/pi/dev/nitrogen/camera && forever start -a -l /dev/null -c bash scripts/run-camera.sh' 
    ;;
  stop)
    echo "Stopping camera"
    killall node
    ;;
  *)
    echo "Usage: /etc/init.d/camera.sh {start|stop}"
    exit 1
    ;;
esac

exit 0
